version: '3'

networks:
  laravel:

services:
  webserver:
    networks:
      - laravel
    depends_on:
      - php
      - mysql
    image: nginx:stable-alpine
    container_name: webserver
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"

  mysql:
    networks:
      - laravel
    image: mysql:5.7.24
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    restart: unless-stopped
    tty: true

  php:
    networks:
      - laravel
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    restart: unless-stopped
    tty: true